/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2022-03-19 21:02:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.plugin_005fextracted.plugin.CrossSiteScripting.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.owasp.webgoat.plugin.GoatHillsFinancial.Employee;
import org.owasp.webgoat.plugin.crosssitescripting.CrossSiteScripting;
import org.owasp.webgoat.session.WebSession;

public final class ViewProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("STAGE 4 FIXES Look for the <-- STAGE 4 - FIX\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\n");

WebSession webSession = ((WebSession)session.getAttribute("websession"));
	Employee employee = (Employee) session.getAttribute("CrossSiteScripting." + CrossSiteScripting.EMPLOYEE_ATTRIBUTE_KEY);
	CrossSiteScripting lesson = (CrossSiteScripting) webSession.getCurrentLesson();
//	int myUserId = getIntSessionAttribute(webSession, "CrossSiteScripting." + CrossSiteScripting.USER_ID);

      out.write("\n");
      out.write("\t\t<div class=\"lesson_title_box\"><strong>Welcome Back </strong><span class=\"lesson_text_db\">");
      out.print(webSession.getUserNameInLesson());
      out.write("</span></div>\n");
      out.write("\t\t<div class=\"lesson_text\">\n");
      out.write("\t\t\t\t<Table>\n");
      out.write("\t\t\t\t<TR><TD>\n");
      out.write("\t\t\t\t\t\tFirst Name:\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getFirstName());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tLast Name:\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t \t");
      out.print(employee.getLastName());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR><TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tStreet: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t<!-- STAGE 4 - FIX  Note that the description value below gets encoded and address1 here is not -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getAddress1());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tCity/State: \n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getAddress2());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR><TD>\n");
      out.write("\t\t\t\t\t\tPhone: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getPhoneNumber());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tStart Date: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getStartDate());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR><TD>\n");
      out.write("\t\t\t    \t\tSSN: \n");
      out.write("\t\t\t    \t</TD>\n");
      out.write("\t\t\t    \t<TD>\n");
      out.write("\t\t\t    \t\t");
      out.print(employee.getSsn());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tSalary: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getSalary());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR><TD>\n");
      out.write("\t\t\t\t\t\tCredit Card: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getCcn());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tCredit Card Limit: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getCcnLimit());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR><TD>\n");
      out.write("\t\t\t\t\t\tComments: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t<!-- Encode data that might contain HTML content to protect against XSS -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      out.print(lesson.htmlEncode(webSession, employee.getPersonalDescription()));
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tManager: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getManager());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\t\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t<TR><TD>\n");
      out.write("\t\t\t\t\t\tDisciplinary Explanation: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getDisciplinaryActionNotes());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\t\t\t\t\n");
      out.write("\t\t\t\t\t\tDisciplinary Action Dates: \n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t\t<TD>\n");
      out.write("\t\t\t\t\t\t");
      out.print(employee.getDisciplinaryActionDate());
      out.write("\n");
      out.write("\t\t\t\t\t</TD>\n");
      out.write("\t\t\t\t</TR>\n");
      out.write("\t\t\t\t</Table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"lesson_buttons_bottom\">\n");
      out.write("\t\t    <table width=\"460\" height=\"20\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                 <tr>\n");
      out.write("                 \t<td width=\"50\">\n");
      out.write("\t\t\t\t\t");
					
					if (webSession.isAuthorizedInLesson(webSession.getUserIdInLesson(), CrossSiteScripting.LISTSTAFF_ACTION))
					{
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<form method=\"POST\" action=\"");
      out.print(webSession.getCurrentLesson().getFormAction());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(CrossSiteScripting.EMPLOYEE_ID);
      out.write("\" value=\"");
      out.print(employee.getId());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(CrossSiteScripting.LISTSTAFF_ACTION);
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t</form></td>\n");
      out.write("\t\t\t\t\t");
 
					}
					
      out.write("\t\t\t\n");
      out.write("\t\t             <td width=\"50\">\n");
      out.write("\t\t\t\t\t");
					
					if (webSession.isAuthorizedInLesson(webSession.getUserIdInLesson(), CrossSiteScripting.EDITPROFILE_ACTION))
					{
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<form method=\"POST\" action=\"");
      out.print(webSession.getCurrentLesson().getFormAction());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(CrossSiteScripting.EMPLOYEE_ID);
      out.write("\" value=\"");
      out.print(employee.getId());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(CrossSiteScripting.EDITPROFILE_ACTION);
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t");
 
					}
					
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("                    <td width=\"60\">\n");
      out.write("\t\t\t\t\t");

					if (webSession.isAuthorizedInLesson(webSession.getUserIdInLesson(), CrossSiteScripting.DELETEPROFILE_ACTION))
					{
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<form method=\"POST\" action=\"");
      out.print(webSession.getCurrentLesson().getFormAction());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
      out.print(CrossSiteScripting.EMPLOYEE_ID);
      out.write("\" value=\"");
      out.print(employee.getId());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(CrossSiteScripting.DELETEPROFILE_ACTION);
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t");
 
					}
					
      out.write("\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("                      <td width=\"190\">&nbsp;</td>\n");
      out.write("                      <td width=\"76\">\n");
      out.write("\t\t\t\t\t\t<form method=\"POST\" action=\"");
      out.print(webSession.getCurrentLesson().getFormAction());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"action\" value=\"");
      out.print(CrossSiteScripting.LOGOUT_ACTION);
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("         \t</table>\n");
      out.write("\t\t</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
